<h2>The __str__ method in exceptions</h2>
<html>
 <head></head>
 <body>
  <p>We have created the exception class called <code class="language-python">NotInBoundsError</code>:</p> 
  <pre><code class="language-python">class NotInBoundsError(Exception):
    def __str__(self):
        return "There is an error!"</code></pre> 
  <p>It prints an error message. The class is already defined in the code, so you use it.</p> 
  <p>First, create the function <code class="language-python">check_integer(i)</code> that checks if the integer in the input lies between <code class="language-python">45</code> and <code class="language-python">67</code>. If it does, the function should return the integer. If not, the <code class="language-python">NotInBoundsError</code> should be raised.</p> 
  <p>Second, create a new function <code class="language-python">error_handling(i)</code>. It should call the <code class="language-python">check_integer(i)</code> function and use the <code class="language-python">try</code>-<code class="language-python">except</code> block to catch the <code class="language-python">NotInBoundsError(i)</code>. If there is an error, print its error message. If there are no errors, print the result of the <code class="language-python">check_integer(i)</code> function.</p>
 </body>
</html><br><b>Sample Input:</b><br><pre><code class="language-no-highlight">8</code></pre><br><b>Sample Output:</b><br><pre><code class="language-no-highlight">There is an error!</code></pre><br><br><br><font color="gray">Memory limit: 256 MB</font><br><font color="gray">Time limit: 15 seconds</font><br><br>
<b>Caution</b><br><br>
You may see errors in your code or execution results due to missing context. Donâ€™t worry about it, just write the solution and press Check.
<br><br>
<a href="https://hyperskill.org/learn/step/10217">Show topic summary</a>